#!/usr/bin/env bash
set -euo pipefail

# Book code-block compilation check.
#
# Every ```rust fence in docs/src/ is a normative claim about the API, and until this
# script existed none of them was ever compiled. CI runs `mdbook build`, which renders the
# book without checking a line of it. That gap let six wrong signatures sit in
# docs/src/reference/shape-composition.md across four RFCs: repeat/tile and their try_ and
# _axis forms were all documented as associated functions when every one takes &self.
#
# `mdbook test` is NOT the tool for this book. It can only pass `-L` to rustdoc, and since
# edition 2018 a doctest resolves `use matten::Tensor` through the extern prelude, which is
# populated by `--extern` alone -- `-L` merely adds a search path. Verified directly: the
# same block fails with `-L` and passes when `--extern matten=<rlib>` is added. mdbook has
# no way to pass that, so every block importing a workspace crate would fail forever.
#
# Instead the blocks are extracted into a generated crate that depends on the workspace by
# path, and compiled with cargo, which resolves deps and features properly. Blocks that are
# deliberately not compilable -- signature listings, and snippets using placeholder
# identifiers such as `t` or `start` -- are tagged ```rust,ignore in the book and skipped
# here, the same marker rustdoc uses. `ignore` is a claim that a block is illustrative;
# keep it rare, because an ignored block is an unchecked one.

DOCS_DIR="docs/src"
WORK="target/doc-code-check"

if [ ! -d "$DOCS_DIR" ]; then
  echo "ERROR: $DOCS_DIR not found (run from the repository root)"
  exit 1
fi

rm -rf "$WORK"
mkdir -p "$WORK/src/bin"

cat >"$WORK/Cargo.toml" <<'EOF'
# Generated by scripts/check-doc-code.sh. Not part of the workspace.
[package]
name = "doc-code-check"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
matten = { path = "../../crates/matten", features = ["dynamic", "serde"] }
matten-data = { path = "../../crates/matten-data", features = ["streaming"] }
matten-mlprep = { path = "../../crates/matten-mlprep" }
matten-ndarray = { path = "../../crates/matten-ndarray" }
matten-stats = { path = "../../crates/matten-stats" }
EOF
printf 'fn main() {}\n' >"$WORK/src/main.rs"

# Extract every non-ignored ```rust fence. One file per block, named for its source so a
# compiler error points straight at the page and line that made the claim.
while IFS= read -r md; do
  awk -v md="$md" -v out="$WORK/src/bin" -v stem="$(echo "$md" | sed -e "s|^$DOCS_DIR/||" -e 's|[/.]|_|g')" '
    /^```rust/ {
      info = substr($0, 8)
      # Skip fences the book marks as illustrative or non-Rust.
      if (info ~ /ignore|text|compile_fail|no_compile/) { skip = 1 } else { skip = 0; inblk = 1; start = NR; n = 0; norun = (info ~ /no_run/) }
      next
    }
    /^```/ && (inblk || skip) {
      if (inblk) {
        # `no_run` blocks are compiled but not executed, exactly as rustdoc treats them:
        # they are legitimate documentation that cannot run here (missing input files,
        # network, or a deliberately panicking demonstration). Encoded in the file name
        # so the runner below can skip them without re-parsing the book.
        f = out "/" (norun ? "norun__" : "") stem "__L" start ".rs"
        # rustdoc convention: a line beginning "# " is hidden in the rendered book but is
        # part of the compiled program. Strip the marker, keep the code.
        body = ""
        for (i = 0; i < n; i++) {
          l = line[i]
          if (l ~ /^#($| )/) { l = substr(l, 3) }
          body = body l "\n"
        }
        printf "// from %s line %d\n", md, start > f
        print "#![allow(unused_imports, unused_variables, dead_code, unused_mut, unused_parens)]" > f
        if (body !~ /use matten::/) {
          print "use matten::{Tensor, MattenError, DataFormat, SliceBuilder, MattenLimits};" > f
        }
        if (body ~ /fn[ \t]+main[ \t]*\(/) {
          printf "%s", body > f
        } else if (body ~ /\?/) {
          # A block using `?` needs a Result-returning main, exactly as rustdoc would.
          print "fn main() -> Result<(), Box<dyn std::error::Error>> {" > f
          printf "%s", body > f
          print "Ok(()) }" > f
        } else {
          print "fn main() {" > f
          printf "%s", body > f
          print "}" > f
        }
        close(f)
        printed++
      }
      inblk = 0; skip = 0
      next
    }
    inblk { line[n++] = $0 }
  ' "$md"
done < <(find "$DOCS_DIR" -name '*.md' | sort)

COUNT=$(find "$WORK/src/bin" -name '*.rs' | wc -l | tr -d ' ')
SKIPPED=$(grep -rc '^```rust.*\(ignore\|text\|compile_fail\)' --include='*.md' "$DOCS_DIR" 2>/dev/null | awk -F: '{s+=$2} END {print s+0}')
echo "=== Compiling $COUNT documented code blocks ($SKIPPED marked illustrative and skipped) ==="

if [ "$COUNT" -eq 0 ]; then
  echo "ERROR: no code blocks were extracted — the extractor is broken, not the docs"
  exit 1
fi

BUILD_LOG="$WORK/build.log"
if ! (cd "$WORK" && cargo build --bins --keep-going --message-format=short) >"$BUILD_LOG" 2>&1; then
  grep -E 'error' "$BUILD_LOG" || cat "$BUILD_LOG"
  echo ""
  echo "ERROR: a documented code block does not compile against the current API."
  echo "       Each failing file is named <page>__L<line>.rs — fix the book at that line,"
  echo "       or mark the fence \`\`\`rust,ignore if it is deliberately illustrative."
  exit 1
fi

# Compiling is not enough. Several pages state results as `expr(); // value` with the
# assertion on a following `#`-hidden line, which mdbook omits from the rendered page --
# the claim and its check are then the same source, rather than a doc copy of a fact the
# tests own separately. A hidden assert_eq! that is built but never EXECUTED proves
# nothing about the value, so every runnable block is run.
RAN=0
NOTRUN=0
FAILED_RUN=""
for bin in "$WORK"/src/bin/*.rs; do
  name="$(basename "$bin" .rs)"
  case "$name" in
    norun__*) NOTRUN=$((NOTRUN + 1)); continue ;;
  esac
  if (cd "$WORK" && cargo run --quiet --bin "$name") >"$WORK/run.log" 2>&1; then
    RAN=$((RAN + 1))
  else
    FAILED_RUN="$FAILED_RUN $name"
    echo "--- $name ---"
    tail -5 "$WORK/run.log"
  fi
done

if [ -n "$FAILED_RUN" ]; then
  echo ""
  echo "ERROR: a documented code block compiled but failed when run —"
  echo "       a stated result does not match what the code actually produces."
  echo "       Fix the book, or mark the fence \`\`\`rust,no_run if it legitimately"
  echo "       cannot execute here (missing input file, deliberate panic)."
  exit 1
fi

echo "All $COUNT documented code blocks compile; $RAN ran clean, $NOTRUN marked no_run."
